server:
  port: 9000
# replaced by using subscription modell
volumes:
  localRepo: 'target/localRepo'

mods:
  - name: 'Mime-Type'
    accepts: 'file'
    links:
      - 'localhost:9001'
    query: '
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>

# Get all files
SELECT DISTINCT ?file WHERE {
 	?dataset dataid:artifact <https://databus.dbpedia.org/dbpedia/databus/databus-data> .
	?dataset dcat:distribution ?distribution .
	?distribution dcat:downloadURL ?file .
}
    '
  - name: 'Line-Count'
    accepts: 'file'
    links:
      - 'localhost:9002'
    query: '
      SELECT * { ?s ?p ?o . }
      '