server:
  port: 9050
spring:
  datasource:
    driver-class-name: 'org.apache.derby.jdbc.EmbeddedDriver'
    username: 'mysqluser'
    password: 'mysqlpass'
    url: 'jdbc:derby:derby;create=true'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
#      ddl-auto: 'update'

mod-server:
  volume: ./target/repo
  web-base: "https://mods.tools.dbpedia.org/main/"
  triple-store:
    db-url: 'jdbc:virtuoso://localhost:11111/charset=UTF-8/'
    db-user: 'dba'
    db-password: 'DasIstDasHausVomNikolaus'
    endpoint: 'http://localhost:8890/sparql'
  schedule:
    online-period: 60000
#    online-check: 5000
    online-check: 3600000
#    task-updates: -1
    task-updates: 3600000

mods:
  - name: 'mimetype'
    accept: 'file'
    select:
    workers:
      - 'http://localhost:14000/modApi'
      - 'http://localhost:14001/modApi'
    query: '
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX dcat:   <http://www.w3.org/ns/dcat#>
PREFIX db:     <https://databus.dbpedia.org/>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>

SELECT * {
{SELECT ?file ?issued ?sha256sum ?downloadURL WHERE {
  ?s dct:publisher <https://yum-yab.github.io/webid.ttl#onto>.
  ?s dataid:file ?file .
  ?s dct:issued ?issued .
  ?s dataid:sha256sum ?sha256sum .
  ?s dcat:downloadURL ?downloadURL .
  ?s dataid-cv:type ?cv .
  FILTER( str(?cv) = "parsed")
  ?s dataid:formatExtension ?ext .
  FILTER( str(?ext) = "nt" )
} LIMIT 10 }
}'
  - name: 'filemetric'
    accept: 'file'
    select: 'file-metrics.ttl'
    workers:
      - 'http://localhost:14010/modApi'
      - 'http://localhost:14011/modApi'
    query: '
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX dcat:   <http://www.w3.org/ns/dcat#>
PREFIX db:     <https://databus.dbpedia.org/>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>

SELECT ?file ?issued ?sha256sum ?downloadURL WHERE {
  ?s dct:publisher <https://yum-yab.github.io/webid.ttl#onto>.
  ?s dataid:file ?file .
  ?s dct:issued ?issued .
  ?s dataid:sha256sum ?sha256sum .
  ?s dcat:downloadURL ?downloadURL .
  ?s dataid-cv:type ?cv .
  FILTER( str(?cv) = "parsed")
  ?s dataid:formatExtension ?ext .
  FILTER( str(?ext) = "nt" )
}'
  - name: 'void'
    accepts:
      - 'file'
    selects:
      - 'rdfVoid.ttl'
    workers:
      - 'http://localhost:14020/modApi'
      - 'http://localhost:14021/modApi'
    query: '
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX dcat:   <http://www.w3.org/ns/dcat#>
PREFIX db:     <https://databus.dbpedia.org/>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>

SELECT ?file ?issued ?sha256sum ?downloadURL WHERE {
 { SELECT ?file ?issued ?sha256sum ?downloadURL WHERE {
  ?s dct:publisher <https://yum-yab.github.io/webid.ttl#onto>.
  ?s dataid:file ?file .
  ?s dct:issued ?issued .
  ?s dataid:sha256sum ?sha256sum .
  ?s dcat:downloadURL ?downloadURL .
  ?s dataid-cv:type ?cv .
  FILTER( str(?cv) = "parsed")
  ?s dataid:formatExtension ?ext .
  FILTER( str(?ext) = "nt" )
  } }
}'
  - name: 'spo'
    accept: 'file'
    select:
    workers:
      - 'http://localhost:14030/modApi'
      - 'http://localhost:14031/modApi'
    query: '
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX dcat:   <http://www.w3.org/ns/dcat#>
PREFIX db:     <https://databus.dbpedia.org/>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>

SELECT ?file ?issued ?sha256sum ?downloadURL WHERE {
  ?s dct:publisher <https://yum-yab.github.io/webid.ttl#onto>.
  ?s dataid:file ?file .
  ?s dct:issued ?issued .
  ?s dataid:sha256sum ?sha256sum .
  ?s dcat:downloadURL ?downloadURL .
  ?s dataid-cv:type ?cv .
  FILTER( str(?cv) = "parsed")
  ?s dataid:formatExtension ?ext .
  FILTER( str(?ext) = "nt" )
}
'