server:
  port: 9050
spring:
  datasource:
    driver-class-name: 'org.apache.derby.jdbc.EmbeddedDriver'
    username: 'mysqluser'
    password: 'mysqlpass'
    url: 'jdbc:derby:derby;create=true'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
#      ddl-auto: 'update'


mod-server:
  volume: ./target/repo
  web-base: "https://mods.tools.dbpedia.org/main/"
  triple-store:
    db-url: 'jdbc:virtuoso://localhost:11111/charset=UTF-8/'
    db-user: 'dba'
    db-password: 'DasIstDasHausVomNikolaus'
    endpoint: 'http://localhost:8890/sparql'
  schedule:
    online-check: 3600000
    task-updates: 3600000

mods:
  - name: 'void'
    accepts:
      - 'file'
    selects:
      - 'rdfVoid.ttl'
    workers:
      - 'http://localhost:14010/modApi'
      - 'http://localhost:14011/modApi'
      - 'http://localhost:14012/modApi'
      - 'http://localhost:14013/modApi'
      - 'http://localhost:14014/modApi'
    query: '
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX dcat:   <http://www.w3.org/ns/dcat#>
PREFIX db:     <https://databus.dbpedia.org/>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>

SELECT ?file ?issued ?sha256sum ?downloadURL WHERE {
 { SELECT ?file ?issued ?sha256sum ?downloadURL WHERE {
  ?s dct:publisher <https://yum-yab.github.io/webid.ttl#onto>.
  ?s dataid:file ?file .
  ?s dct:issued ?issued .
  ?s dataid:sha256sum ?sha256sum .
  ?s dcat:downloadURL ?downloadURL .
  ?s dataid-cv:type ?cv .
  FILTER( str(?cv) = "parsed")
  ?s dataid:formatExtension ?ext .
  FILTER( str(?ext) = "nt" )
  } LIMIT 10 }
}'
#  - name: 'filemetric'
#    accept: 'file'
#    select: 'rdfVoid.ttl'
#    workers:
#      - 'http://localhost:32798/modApi'
#      - 'http://localhost:32799/modApi'
#      - 'http://localhost:32800/modApi'
#    query: '
#PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
#PREFIX dct:    <http://purl.org/dc/terms/>
#PREFIX dcat:   <http://www.w3.org/ns/dcat#>
#PREFIX db:     <https://databus.dbpedia.org/>
#PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
#
#SELECT ?file ?issued ?sha256sum ?downloadURL WHERE {
#  ?s dct:publisher <https://yum-yab.github.io/webid.ttl#onto>.
#  ?s dataid:file ?file .
#  ?s dct:issued ?issued .
#  ?s dataid:sha256sum ?sha256sum .
#  ?s dcat:downloadURL ?downloadURL .
#  ?s dataid-cv:type ?cv .
#  FILTER( str(?cv) = "parsed")
#  ?s dataid:formatExtension ?ext .
#  FILTER( str(?ext) = "nt" )
#}'